title: Metadata
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:

        metadata:
          type: tab
          title: Metadata
          fields:
            metadata:
              name: meta
              type: section
              title: Metadata

              fields:
                header.refresh:
                  type: text
                  label: Refresh
                  default: 30
                  validate:
                    type: int
                header.generator:
                  type: text
                  label: Generator
                  default: Grav
                header.description:
                  type: text
                  label: Description
                header.keywords:
                  type: text
                  label: Keywords
                header.author:
                  type: text
                  label: Author
                header.robots:
                  type: text
                  label: Robots
                  default: "index, follow"
